# NumPy
``numpy` adalah library yang sangat populer di Python untuk melakukan operasi pada array multidimensi.

## 1. Import library NumPy

In [10]:
import numpy as np

## 2. Array dasar

In [11]:
# membuat array
a = np.array([1, 2, 3, 4, 5]) # Array 1D
b = np.array([[1, 2, 3], [4, 5, 6]]) # Array 2D
x = np.array([6,3,8,2,9]) # Array 1D


In [12]:
# Tipe data (dtype) dan shape
print("a".center(50, "-"))
print(a.dtype)
print(a.shape)
print(a.ndim)
print("b".center(50, "-"))
print(b.dtype)
print(b.shape)
print(b.ndim)



------------------------a-------------------------
int64
(5,)
1
------------------------b-------------------------
int64
(2, 3)
2


## 3. Operasi dasar

In [13]:
# Penjumlahan, pengurangan, perkalian
print(a + 1)
print(a * 2)
print(a ** 2)


[2 3 4 5 6]
[ 2  4  6  8 10]
[ 1  4  9 16 25]


In [14]:
# Operasi antara array
print(a+x)
print(np.dot(a,x))
# Jika array tidak memiliki dimensi yang sama, maka akan terjadi error

[ 7  5 11  6 14]
89


## 4. Index dan slicing

In [15]:
print(a[0])
print(a[1:3])
print(b[1,0])

1
[2 3]
4


# 5. Broadcasting

In [ ]:
a = np.array([1, 2, 3,4])
b = np.array([[1], [2], [3]])
print(a + b)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


## 6. Reshape dan Transpose

In [46]:
a.reshape(3, 1)

print(a.T)

[1 2 3]


## 7. Statistik Dasar

In [ ]:
print(np.mean(a))
print(np.std(a))
print(np.max(a))
print(np.min(a))
print(np.sum(a, axis=0))


2.0
0.816496580927726
3
1
6


## 8. Fungsi Khusus

In [49]:
print(np.zeros((3, 3)))
print(np.ones((2, 2)))
print(np.eye(3))
print(np.random.rand(3, 3))
print(np.arange(0, 10, 2))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.02995582 0.81988786 0.64949354]
 [0.524706   0.24648942 0.24449959]
 [0.57152775 0.44497392 0.5640544 ]]
[0 2 4 6 8]


## 9. Operasi Matriks dan Vektor

In [51]:
## Matriks fitur dan target
X = np.array([[1, 2], [3, 4], [5, 6]])
y = np.array([1, 2, 3])
print(X)
print(y)


[[1 2]
 [3 4]
 [5 6]]
[1 2 3]


In [52]:
## Transpose dan perkalian
XT = X.T
XT_X = XT @ X  # mirip dengan X.T.dot(X)

print(XT)
print(XT_X)

[[1 3 5]
 [2 4 6]]
[[35 44]
 [44 56]]


# 9. Standarisasi Fitur


In [53]:
X_mean = X.mean(axis=0)
X_std = X.std(axis=0)
X_scaled = (X - X_mean) / X_std

print(X_scaled)
print(X_std)
print(X_scaled)


[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]
[1.63299316 1.63299316]
[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]


# 10. Implementasi Regresi Linier Sederhana (tanpa library)

In [54]:
# y = wX + b
X = np.array([[1], [2], [3]])
y = np.array([2, 4, 6])
w = np.linalg.inv(X.T @ X) @ X.T @ y

print(X)
print(y)
print(y)

[[1]
 [2]
 [3]]
[2 4 6]
[2 4 6]
